### ISSUE TITLE
Telemetry check causes crash when hidepid=2 is enabled

### ISSUE THREAD

**Issue by sn0w** [dotnet/toolset#3668]
First off, I'm not sure if this is the correct place to report this issue.
If I'm reporting on the wrong tracker, please direct me somewhere else.

On my server the `/proc` directory is mounted with the mount option `hidepid=2`. This means that `/proc` only contains pid-folders for programs that the current user owns. (see https://manned.org/proc.5 fore more information).

When telemetry is enabled, the dotnet CLI seems to execute a check to find out whether or not it's running in docker. A function called `ReadProcToDetectDockerInLinux()` attempts to open `/proc/1/cgroup`. However, on `hidepid=2`, there is no `/proc/1` directory. The CLI crashes with a `DirectoryNotFoundException`. Setting `DOTNET_CLI_TELEMETRY_OPTOUT=1` "fixes" this crash.

## Steps to reproduce

Run any command with telemetry enabled on a system with `hidepid=2`.

## Expected  behavior

The command works.

## Actual behavior

```txt
sn0w@noire ~> dotnet help
Assertion Failed
System.IO.DirectoryNotFoundException: Could not find a part of the path '/proc/1/cgroup'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.DotNet.Cli.Telemetry.DockerContainerDetectorForTelemetry.ReadProcToDetectDockerInLinux()
   at Microsoft.DotNet.Cli.Telemetry.DockerContainerDetectorForTelemetry.IsDockerContainer()
   at Microsoft.DotNet.Cli.Telemetry.TelemetryCommonProperties.<GetTelemetryCommonProperties>b__23_0()
   at Microsoft.DotNet.Configurer.UserLevelCacheWriter.RunWithCache(String cacheKey, Func`1 getValueToCache)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryCommonProperties.GetTelemetryCommonProperties()
   at Microsoft.DotNet.Cli.Telemetry.Telemetry.InitializeTelemetry()

   at Microsoft.DotNet.Cli.Telemetry.Telemetry.InitializeTelemetry()
   at Microsoft.DotNet.Cli.Telemetry.Telemetry.<.ctor>b__12_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
fish: “dotnet help” terminated by signal SIGABRT (Abort)
```

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.2.108/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.6 [/opt/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by Folling** [comment]
Facing the same issue here, any updates on this?
